name_or_path: mistralai/Mistral-7B-v0.1
tokenizer_name_or_path: mistralai/Mistral-7B-v0.1
archive: null
ref_archive_for_eval: null
block_name: MistralDecoderLayer

policy_dtype: bfloat16
fsdp_policy_mp: null
reference_dtype: bfloat16