model_name_or_path: google/flan-t5-xl
tokenizer_name: google/flan-t5-xl
# currently supported task_type can be either CAUSAL_LM or SEQ_2_SEQ_LM
task_type: "SEQ_2_SEQ_LM"

dtype: float32

use_lora: false
metric: rouge
num_beams: 1



